name = "runpod-proxy"
main = "runpod-proxy.js"
compatibility_date = "2024-08-20"

# Environment variables for your RunPod URLs
[env.production.vars]
DEFAULT_IMAGE_URL = "https://9wc6zqlr5p7i6a-3001.proxy.runpod.net/"
RUNPOD_IMAGE_URL = "https://9wc6zqlr5p7i6a-3001.proxy.runpod.net/"
RUNPOD_IMAGE_MODIFY_URL = "https://9wc6zqlr5p7i6a-3001.proxy.runpod.net/"
# Add your other RunPod URLs here
# RUNPOD_TEXT_URL = "your-text-runpod-url"
# RUNPOD_VIDEO_URL = "your-video-runpod-url"

[env.staging.vars]
DEFAULT_IMAGE_URL = "https://9wc6zqlr5p7i6a-3001.proxy.runpod.net/"
RUNPOD_IMAGE_URL = "https://9wc6zqlr5p7i6a-3001.proxy.runpod.net/"
RUNPOD_IMAGE_MODIFY_URL = "https://9wc6zqlr5p7i6a-3001.proxy.runpod.net/"

# Routes for your workers.dev domain (default)
# You can add a custom domain later in the Cloudflare dashboard
# [[route]]
# pattern = "runpod.yourdomain.com/*"
# zone_name = "yourdomain.com"
