name = "runpod-proxy"
main = "runpod-proxy.js"
compatibility_date = "2024-08-20"

# Environment variables for your RunPod URLs
[env.production.vars]
DEFAULT_IMAGE_URL = "https://64e5p2jm3e5r3k-3001.proxy.runpod.net/"
# Add your other RunPod URLs here
# RUNPOD_TEXT_URL = "your-text-runpod-url"
# RUNPOD_VIDEO_URL = "your-video-runpod-url"
# RUNPOD_IMAGE_MODIFY_URL = "your-modify-runpod-url"

[env.staging.vars]
DEFAULT_IMAGE_URL = "https://64e5p2jm3e5r3k-3001.proxy.runpod.net/"

# Routes for your custom domain
[[route]]
pattern = "runpod.yourdomain.com/*"
zone_name = "yourdomain.com"
