name = "101world-ai-api"
main = "src/index.ts"
compatibility_date = "2024-08-26"

# Cloudflare Workers AI binding
[ai]
binding = "AI"

# R2 bucket for document storage
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "101world-documents"

# Vectorize for semantic search
[[vectorize]]
binding = "VECTORIZE"
index_name = "embeddings"

# KV for caching and session storage
[[kv_namespaces]]
binding = "CACHE"
id = "7e948450cb224571b9c047378bd9afe9"
preview_id = "9bab3f0914d34694967286bf2aad395a"

# Environment variables
[vars]
ENVIRONMENT = "production"
API_VERSION = "v1"

# Secrets (set via wrangler secret put)
# OPENAI_API_KEY = "your-fallback-key"
# CLERK_SECRET_KEY = "your-clerk-secret"
